name: 返利网

on:
  workflow_dispatch:
  schedule:
     - cron: '0 2,9,23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/heeroyuy7/heeroyuy7.git ~/heeroyuy7
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/heeroyuy7
          git checkout ZIYE
          npm install
      - name: '运行 【返利网】'
        run: |
          cd ~/heeroyuy7
          node Task/flw.js
        env:
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
